// Code generated by protoc-gen-go.
// source: transaction.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	transaction.proto

It has these top-level messages:
	Transaction
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Transaction struct {
	Source           []byte  `protobuf:"bytes,1,req,name=source" json:"source,omitempty"`
	Destination      []byte  `protobuf:"bytes,2,req,name=destination" json:"destination,omitempty"`
	Signature        []byte  `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	Amount           *uint32 `protobuf:"varint,4,req,name=amount" json:"amount,omitempty"`
	Nonce            *uint64 `protobuf:"varint,5,req,name=nonce" json:"nonce,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Transaction) GetSource() []byte {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Transaction) GetDestination() []byte {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Transaction) GetAmount() uint32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func init() {
	proto.RegisterType((*Transaction)(nil), "main.Transaction")
}

var fileDescriptor0 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x8c, 0x31, 0x0e, 0xc2, 0x30,
	0x0c, 0x45, 0x45, 0x49, 0x91, 0x70, 0x29, 0x52, 0xc3, 0x92, 0x11, 0x31, 0x31, 0x71, 0x1a, 0x2e,
	0x60, 0xb5, 0x11, 0xf2, 0x50, 0x1b, 0xd9, 0xce, 0xfd, 0x31, 0x5d, 0x3a, 0xbe, 0xf7, 0xf4, 0x3f,
	0x4c, 0xae, 0xc8, 0x86, 0xb3, 0x93, 0xf0, 0xeb, 0xab, 0xe2, 0x92, 0xd3, 0x8a, 0xc4, 0x8f, 0x05,
	0x86, 0xf7, 0x9e, 0xf2, 0x15, 0x4e, 0x26, 0x4d, 0xe7, 0x5a, 0x0e, 0xf7, 0xee, 0x79, 0xc9, 0x37,
	0x18, 0x96, 0x6a, 0x4e, 0x8c, 0xff, 0x5c, 0xba, 0x4d, 0x4e, 0x70, 0x36, 0xfa, 0x84, 0x6a, 0x5a,
	0xcb, 0x71, 0x53, 0xb1, 0xc3, 0x55, 0x1a, 0x7b, 0x49, 0xc1, 0x63, 0x1e, 0xa1, 0x67, 0xe1, 0xb8,
	0xe9, 0x03, 0xd3, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x85, 0x94, 0x45, 0x9a, 0x7f, 0x00, 0x00, 0x00,
}
